services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: letvagas
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./database/init_db.sql:/docker-entrypoint-initdb.d/init.sql

  letvagas:
    image: letvagas
    restart: on-failure:5
    environment:
      PORT: 3000
      DATABASE_URL: postgres://postgres:postgres@db:5432/letvagas
    ports:
      - 3000:3000
    depends_on:
      - db

volumes:
  pgdata:
